# Postgres Deployment
# Manage the DB pod

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres

spec:
  replicas: 1 # Only 1 pod for data persistence
  selector:
    matchLabels:
      app: inventory-postgres-app
  template:
    metadata:
      labels:
        app: inventory-postgres-app
    spec:
      containers:
        # This'll be the postgres pod
      - name: postgres 
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef: 
                name: inventory-postgres-config 
                key: postgres_db
          - name: POSTGRES_USER #Create an environment variable
            valueFrom:
              configMapKeyRef:  # It'll be found in a config map.
                name: inventory-postgres-config #This is the name of the ConfigMap
                key: postgres_user #This is what the key is named in the ConfigMap
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: # This one will be found in a Secret
                name: inventory-postgres-secret
                key: postgres_pwd
          - name: PGDATA 
            value: /var/lib/postgresql/data/pgdata # Tells postgres where to put the data
        # These are instructions on how to find the volume we're making    
        volumeMounts:
        - name: postgres-data #The name of the volume
          mountPath: /var/lib/postgresql/data
          # This should define the volume, and connect it to the claim.
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: inventory-postgres-volume

---
# Postgres Service
# Manage DB connections
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres-app
spec:
  selector:
    app: inventory-postgres-app
  ports:
  - port: 5432
    targetPort: 5432


---
#ConfigMap
# Configuration settings for postgres

apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-postgres-config
data: #Assign the environment variables for DB access
  postgres_user: inventory
  postgres_db: inventory
  postgres_url: jdbc:postgresql://inventory-postgres-app:5432/inventory
---
# Secret
# Stores secret config, like passwords
apiVersion: v1
kind: Secret
metadata:
  name: inventory-postgres-secret
type: Opaque # Generic user-defined secret
stringData:
  postgres_pwd: "secret" #Just the password environment variable


---
# PVC - Persistent Volume Claim
# Let's ask for a volume that can be accesed by 1 pod at a time.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # 1 Gig of storage
  volumeMode: Filesystem # Default volume setting.
