spring.application.name=category-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:inventorydb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

server.port = 8081

spring.jpa.hibernate.ddl-auto=update


#H2 Driver - leaving this blank to let spring determine driver based off of the url
# spring.datasource.driverClassName=org.h2.Driver

# Enable the H2 web console
# spring.h2.console.enabled=false